### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by sgven** [JoshuaWise/cost#1]
let config = require('yylib-react/dist/config/webpack.config');
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
and
 Failed at the cost@1.0.0 dev-cost script 'webpack-dev-server --devtool eval --display-error-details --progress --colors --hot --inline --config cost.config.js '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cost package,
npm ERR! not with npm itself.

**Comment by sgven** [comment]
块级作用域下的声明（let, const, function, class）等在严格模式下是不被支持的。
其实就是说ES6新语法在目前的环境下是不被支持的，可用一些工具对代码进行转化；

webpack.config.js //用到了严格模式
{
'use strict';
...

}

**Comment by JoshuaWise** [comment]
I'm not longer interested in maintaining this project. I recommend forking it or finding a different solution.
